# PURPOSE: overrides Google dns servers with SAP ones
#
# 'docker build' will cause the ONBUILD trigger in the parent image to perform the 'ADD ./config /config/'
#

FROM progrium/consul

MAINTAINER  gerald.braunwarth@sap.com
